// GET LOGIN API
export const USER_SIGNIN_API = "SIGIN_API";
export const GET_TASK_API = "GET_TASK_API";
export const GET_API_SUCCESS = "GET_API_SUCCESS";
export const GET_API_FAILED = "GET_API_FAILED ";

export const USLOGIN_ACTION = "LOGIN_SUCCESSFULLY";

// GET - PROJECT CATEGORY
export const API_PROJECT_CATEGORY = "GET_ALL_PROJECT_CATEGORY_SAGA";

// GET ALL LIST
export const GET_ALL_LIST = "GET_ALL_PROJECT_SAGA";

// GET PROJECT DETAIl
export const GET_PROJECT_DETAIL = "GET_PROJECT_DETAIL_API_SAGA";

// CREATE - PROJECT
export const API_CREATE_PROJECT = "CREATE_PROJECT_SAGA";

// ModalHOC Reducer

export const OPEN_MODAL = "OPEN_MODAL_POPUP";
export const CLOSE_MODAL = "CLOSE_MODAL_POPUP";
export const OPEN_EDIT_FORM = "OPEN_FORM_EDIT_PROJECT";
export const SET_SUBMIT_FORM = "SET_SUBMIT_EDIT_PROJECT";

// EditFormProject Reducer
export const EDIT_PROJECT_FORM = "EDIT_PROJECT_FORM";
export const PUT_PROJECT_DETAIL = "PUT_PROJECT_DETAIL";
// PUT - Update Project Saga
export const UPDATE_PROJECT = "UPDATE_PROJECT_SAGA";

// DELETE - Delete Project saga
export const DELETE_PROJECT = "DELETE_PROJECT_SAGA";

// USER API
export const GET_SEARCH_USER = "GET_SEARCH_USER";
export const GET_USER_API = "GET_USER_FROM_API";

// ADD USER
export const ADD_USER_PROJECT = "ADD_USER_PROJECT_FROM_API";

// REMOVE USER
export const REMOVE_USER_PROJECT = "REMOVE_USER_PROJECT_API";
