// GET LOGIN API
export const USER_SIGNIN_API = "SIGIN_API";
export const GET_TASK_API = "GET_TASK_API";
export const GET_API_SUCCESS = "GET_API_SUCCESS";
export const GET_API_FAILED = "GET_API_FAILED ";

export const USLOGIN_ACTION = "LOGIN_SUCCESSFULLY";

// GET PROJECT CATEGORY
export const API_PROJECT_CATEGORY =
  "GET_ALL_PROJECT_CATEGORY_SAGA_SUCCESSFULLY";

// CREATE PROJECT
export const API_CREATE_PROJECT = "CREATE_PROJECT_SAGA_SUCCESSFULLY";
