export const GET_ALL_TASK_TYPE = "GET_ALL_TASK_TYPE";
export const GET_ALL_TASK_TYPE_SAGA = "GET_ALL_TASK_TYPE_SAGA";
export const CREATE_TASK_SAGA = "CREATE_TASK_SAGA";
export const SET_SUBMIT_CREATE_TASK = "SET_SUBMIT_CREATE_TASK";
