export const GET_ALL_TASK_TYPE = "GET_ALL_TASK_TYPE";
export const GET_ALL_TASK_TYPE_SAGA = "GET_ALL_TASK_TYPE_SAGA";
export const CREATE_TASK_SAGA = "CREATE_TASK_SAGA";
export const SET_SUBMIT_CREATE_TASK = "SET_SUBMIT_CREATE_TASK";

export const GET_TASK_DETAL_REDUCER = "GET_TASK_DETAL_REDUCER";
export const GET_TASK_DETAL_SAGA = "GET_TASK_DETAL_SAGA";

export const UPDATE_TASK_STATUS_SAGA = "UPDATE_TASK_STATUS_SAGA";

export const CHANGE_TASK_MODAL = "CHANGE_TASK_MODAL";
export const HANDLE_CHANGE_TASK_POST_API_SAGA =
  "HANDLE_CHANGE_TASK_POST_API_SAGA";

export const CHANGE_ASSIGNESS = "CHANGE_ASSIGNESS";
export const REMOVE_USER_TASK = "REMOVE_USER_TASK";
